### ISSUE TITLE
Rename the package name to ngdart_cli

### ISSUE THREAD

**Issue by IgorBabalich** [GZGavinZhao/ngdart#3]
Rename the existing ngdart package utility to ngdart_cli, so the package name will be available for the main angular package of AngularDart Community

**Comment by GZGavinZhao** [comment]
I'll do the rename of the repository later.

**Comment by GZGavinZhao** [comment]
There's no need to opt-out of null safety. The current published version of `ngcomponents` works fine with null safe code.

**Comment by IgorBabalich** [comment]
Removed // @Dart=2.9 from the web/main.dart template,
updated ngcomponents version, so it takes the last published version 1.1.0+1, 
but massive complains are still present like 
// @dart=2.9
^^^^^^^^^^^^
Error: Cannot run with sound null safety, because the following dependencies 
don't support null safety: 
- package:ngcomponents

Had to revert back the sdk version to 2.10.0 to move forward, so a generated project could work,
i.e. null safety was turned off by existing ngdart utility with sdk constraint 2.10.0, so keeping the same version as before for now.

I will join to help migrate ngcomponents, so we could quicker publish a full null safety sound version of this package.

**Comment by GZGavinZhao** [comment]
@IgorBabalich Weird, I remember it used to work. I'll check that. Just for reference, what SDK are you on (`dart --version`)?

**Comment by GZGavinZhao** [comment]
@IgorBabalich How about this: let's keep our steps small. Don't change anything related to the template code for now. Just do the renaming and nothing else. We'll narrow down the problem later.

Also, the template part (the code that `ngdart` generates) has no relation to the null safety of this package, so it is not an area of concern here :)

**Comment by IgorBabalich** [comment]
> @IgorBabalich Weird, I remember it used to work. I'll check that. Just for reference, what SDK are you on (`dart --version`)?
Ok.
Dart SDK version: 2.17.1 (stable) (Tue May 17 17:58:21 2022 +0000) on "windows_x64"
