### ISSUE TITLE
ngdart bin installation

### ISSUE THREAD

**Issue by kurtwilliams14** [GZGavinZhao/ngdart#5]
It appears that ngdart is not being installed in the bin directory for v7+. Installing v1+ seems to install bin and works as expected

Steps to reproduce

dart pub global activate ngdart 7.1.1
ls ~/.pub-cache/bin
see ngdart is not present

dart pub global activate ngdart 1.1.0
ls ~/.pub-cache/bin
see ngdart is present and executable

**Comment by GZGavinZhao** [comment]
@kurtwilliams14 Please run `dart pub global activate ngdart_cli` instead of `dart pub global activate ngdart`. Currently the CLI is developed and versioned separately from the main libraries.
