### ISSUE TITLE
ngdart create still uses stagehand templates calling angular package

### ISSUE THREAD

**Issue by dvorapa** [GZGavinZhao/ngdart#7]
**Steps to reproduce**
1. Run `pub global activate webdev && pub global activate ngdart && pub global activate ngdart_cli`
2. Run `ngdart create myproject`
3. Open newly created myproject folder
4. In its pubspec.yaml it still requires _angular_ package, in dart files it imports _package:angular/angular.dart_

This should be changed to ngdart right? Or am I missing something?

**Comment by GZGavinZhao** [comment]
You're right that this should not happen. The reason is that just two weeks ago `ngcomponents` was still using `angular`, so I haven't updated the template yet. Now we can update the template to use `ngdart`.

Side note: you don't need to `dart pub global activate ngdart`.

**Comment by GZGavinZhao** [comment]
Fixed via 983f636ee93dff887009252ac1caa8bfcb6ac132. Feel free to reopen if the issue still exists after upgrading to v1.3.0.
